dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  provider: ^6.0.0
  tensorflow_lite_flutter_helper: ^0.2.0
  firebase_auth: ^3.1.5
  # Outras bibliotecas úteis para segurança, criptografia, e autenticação
